# Generated by Django 2.2.5 on 2019-10-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20191007_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_calendarioservicio',
            name='domicilio',
            field=models.CharField(default=22, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tb_calendarioservicio',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tb_calendarioservicio',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
    ]
