# Generated by Django 2.2.5 on 2019-10-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191009_1133'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tb_calendarioservicio',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tb_catalogoservicio',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tb_usuario',
            managers=[
            ],
        ),
    ]
