# Generated by Django 2.2.5 on 2019-10-11 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20191009_1136'),
        ('main_app', '0007_auto_20191007_1843'),
    ]

    operations = [
    ]
